language: python
python:
  - '3.6'
  - '3.7'
addons:
  apt:
    packages:
      - coinor-cbc
install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - flake8
  - py.test
